export default {
    groups: ['users', 'premium', 'admin', 'editor', 'moderator'],
    users: [
        {
            id: 1,
            name: 'Adam Smith',
            age: 26,
            gender: 'male',
            lookingfor: 'female',
            location: 'Boston',
            member: ['users', 'premium', 'admin', 'editor', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/10.jpg',
        },
        {
            id: 2,
            name: 'Vanessa Ward',
            age: 49,
            gender: 'female',
            lookingfor: 'male',
            location: 'New York',
            member: ['users', 'editor', 'moderator'],
            image: 'https://randomuser.me/api/portraits/women/11.jpg',
        },
        {
            id: 3,
            name: 'Ronald Blair',
            age: 66,
            gender: 'male',
            lookingfor: 'female',
            location: 'Miami',
            member: ['users', 'editor', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/12.jpg',
        },
        {
            id: 4,
            name: 'Miranda Jones',
            age: 31,
            gender: 'female',
            lookingfor: 'male',
            location: 'Huston',
            member: ['users', 'admin'],
            image: 'https://randomuser.me/api/portraits/women/13.jpg',
        },
        {
            id: 5,
            name: 'Ken Spider',
            age: 19,
            gender: 'male',
            lookingfor: 'male',
            location: 'Los Angeles',
            member: ['users', 'admin', 'editor', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/14.jpg',
        },
        {
            id: 6,
            name: 'Patricia Adams',
            age: 37,
            gender: 'female',
            lookingfor: 'female',
            location: 'San Diego',
            member: ['users', 'premium'],
            image: 'https://randomuser.me/api/portraits/women/15.jpg',
        },
        {
            id: 7,
            name: 'Stanley Johanson',
            age: 41,
            gender: 'male',
            lookingfor: 'male',
            location: 'Chicago',
            member: ['users', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/16.jpg',
        },
        {
            id: 8,
            name: 'Emily Sanders',
            age: 29,
            gender: 'female',
            lookingfor: 'female',
            location: 'Washington',
            member: ['users', 'premium'],
            image: 'https://randomuser.me/api/portraits/women/17.jpg',
        },
        {
            id: 9,
            name: 'Roman Spilner',
            age: 21,
            gender: 'male',
            lookingfor: 'female',
            location: 'Denver',
            member: ['users', 'editor'],
            image: 'https://randomuser.me/api/portraits/men/20.jpg',
        },
        {
            id: 10,
            name: 'Angela Ravel',
            age: 34,
            gender: 'female',
            lookingfor: 'male',
            location: 'San Antonio',
            member: ['users', 'premium', 'editor'],
            image: 'https://randomuser.me/api/portraits/women/21.jpg',
        },
        {
            id: 11,
            name: 'Donald Tusk',
            age: 71,
            gender: 'male',
            lookingfor: 'female',
            location: 'Vancuver',
            member: ['users', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/22.jpg',
        },
        {
            id: 12,
            name: 'Sandra Valasqez',
            age: 22,
            gender: 'female',
            lookingfor: 'male',
            location: 'London',
            member: ['users', 'premium'],
            image: 'https://randomuser.me/api/portraits/women/23.jpg',
        },
        {
            id: 13,
            name: 'Kristian Shikorsky',
            age: 18,
            gender: 'male',
            lookingfor: 'male',
            location: 'Sacramento',
            member: ['users', 'editor'],
            image: 'https://randomuser.me/api/portraits/men/24.jpg',
        },
        {
            id: 14,
            name: 'Rachel Green',
            age: 29,
            gender: 'female',
            lookingfor: 'female',
            location: 'Seattle',
            member: ['users', 'premium'],
            image: 'https://randomuser.me/api/portraits/women/25.jpg',
        },
        {
            id: 15,
            name: 'Antony DiAngelo',
            age: 44,
            gender: 'male',
            lookingfor: 'male',
            location: 'Phoenix',
            member: ['users', 'premium', 'editor', 'moderator'],
            image: 'https://randomuser.me/api/portraits/men/26.jpg',
        },
        {
            id: 16,
            name: 'Kate Alison',
            age: 52,
            gender: 'female',
            lookingfor: 'female',
            location: 'Detroit',
            member: ['users', 'premium', 'editor'],
            image: 'https://randomuser.me/api/portraits/women/27.jpg',
        },
    ],
};
